FROM {{ httpd_image }}
COPY httpd.conf "{{ httpd_server_root }}/conf/"
COPY .creds "{{ httpd_server_root }}/"
COPY localhost.key "{{ httpd_server_root }}/"
COPY localhost.crt "{{ httpd_server_root }}/"
