FROM docker.io/httpd:latest
COPY web_source/ "{{ httpd_server_root }}/htdocs/"
COPY .htaccess "{{ httpd_server_root }}/htdocs/"
COPY httpd.conf "{{ httpd_server_root }}/conf/"
COPY .creds "{{ httpd_server_root }}/"
COPY localhost.key "{{ httpd_server_root }}/"
COPY localhost.crt "{{ httpd_server_root }}/"
