---
- name: 'Podman Servers Configuration'
  hosts: ContainerVM
  remote_user: "{{ podman_ssh_login }}"
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:
    - name: Install podman (state=present is optional)
      ansible.builtin.dnf:
        name: "{{ podman_package }}"
        state: present
    - name: Install git cli
      ansible.builtin.dnf:
        name: "git"
        state: present
    - name: Install Python3
      ansible.builtin.dnf:
        name: "python3"
        state: present
    - name: Install passlib package
      ansible.builtin.pip:
        name: passlib
    - name: Install python3 package cryptography
      ansible.builtin.pip:
        name: cryptography

