---
- name: 'OCI Image creation for webservers'
  hosts: ContainerVM
  remote_user: "{{ podman_ssh_login }}"
  become: true
  vars_files:
    - vars/01_02_vars.yaml
  vars: #estas variables son locales y se necesitan exclusivamente en el ámbito de este playbook.
    oci_folder: "/home/{{ podman_ssh_login }}/oci_webserver"
    pkey_path: "{{ oci_folder}}/localhost.key"
    csr_path: "{{ oci_folder}}/localhost.csr"
    crt_path: "{{ oci_folder}}/localhost.crt"
    web_source: "{{ oci_folder }}/web_source"
    #    ansible_python_interpreter: /usr/bin/python3 #force to use python3 binary to process this playbook. If not, some modules did work as expected.
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ oci_folder }}"
        state: directory
        mode: '0755'
         #    - name: Creating a apache2 password file "{{ oci_folder }}"/.creds #no es necesario, el siguiente paso crea el fichero si no existe.
        #ansible.builtin.file: 
        #path: "{{ oci_folder }}/.creds"
        #state: touch

    - name: Create a user "{{ htpasswd_user }}" to restrict web access through .hpasswd file.
      community.general.htpasswd:
        path: "{{ oci_folder}}/.creds"
        name: "{{ htpasswd_user }}"
        password: "{{ htpasswd_passwd }}"
        owner: root
        group: root
        mode: '0644'
 
    - name: Generate an OpenSSL private key 2048 and store it on "{{ pkey_path }}"
      community.crypto.openssl_privatekey:
        path: "{{ pkey_path }}"
        size: 2048
    - name: Generate an OpenSSL CSR and store it on "{{ csr_path }}"
      community.crypto.openssl_csr:
        path: "{{ csr_path }}"
        privatekey_path: "{{ pkey_path }}"
        country_name: ES
        organization_name: casopractico2
        email_address: jdoe@gmail.com
        common_name: www.unir.com

    - name: Generate a Self Signed OpenSSL certificate and store it on "{{ crt_path }}"
      community.crypto.x509_certificate:
        path: "{{ crt_path }}"
        privatekey_path: "{{ pkey_path }}"
        csr_path: "{{ csr_path }}"
        provider: selfsigned

    - name: Create a folder for web source code "{{ web_source }}"
      ansible.builtin.file:
         path: "{{ web_source }}"
         state: directory
         mode: '0755'
    - name: Git clone web source code "{{ web_repo }}"
      ansible.builtin.git:
        repo: "{{ web_repo }}"
        dest: "{{ web_source }}"
        version: "{{ web_repo_branch }}"
    - name: Template a httpd.j2 to "{{ oci_folder }}/httpd.conf"
      ansible.builtin.template:
        src: templates/httpd.j2
        dest: "{{ oci_folder }}/httpd.conf"
        owner: root
        group: root
        mode: '0644'
    - name: Template a Containerfile.j2 to "{{ oci_folder }}/Containerfile"
      ansible.builtin.template:
        src: templates/Containerfile.j2
        dest: "{{ oci_folder }}/Containerfile"
        owner: root
        group: root
        mode: '0644'
    - name: Template a .htaccess.j2 to "{{ oci_folder }}/.htaccess"
      ansible.builtin.template:
        src: templates/htaccess.j2
        dest: "{{ oci_folder }}/.htaccess"
        owner: root
        group: root
        mode: '0644'
    - name: Build OCI Image.
      containers.podman.podman_image:
         name: "{{ image_name }}"
         path: "{{ oci_folder }}"
         tag: "{{ image_tag }}"
         build:
           cache: no
           force_rm: true
           format: oci
           annotation:
             app: apache2
             function: web-server
             info: Web server OCI for CasoPractico2 Unir
             # extra_args: "--build-arg KEY=value"
         push: true
         username: "{{ az_acr_user }}"
         password: "{{ az_acr_passwd }}"
         push_args:
           dest: "{{ az_acr_url }}/{{ acr_repository }}"
