---
- name: 'Podman Image build and push to ACR'
  hosts: ContainerVM
  remote_user: "{{ podman_ssh_login }}"
  become: true
  vars_files:
    - vars/02_vars.yaml 
  tasks:
    - name: Print version
      debug:
        msg: "Acr URL:  {{ az_acr_url }}/{{ podman_acr_folder }}"
    - name: Build OCI Image.
      containers.podman.podman_image:
         name: docker.io/ubuntu/apache2
         path: /path/to/build/dir
        build:
           cache: no
           force_rm: true
           format: oci
           annotation:
             app: apache2
             function: web-server
             info: Web server OCI for CasoPractico2 Unir
             # extra_args: "--build-arg KEY=value"
        push: true
        username: "{{ az_acr_user }}"
        password: "{{ az_acr_passwd }}"
        push_args:
          dest: "{{ az_acr_url }}/{{ podman_acr_folder }}"
